version: '3.2'
services:
  api:
    container_name: api
    image: api
    build: api/.
    ports:
      - 8901:3000
    environment:
      - MONGO_URL=mongodb://mongo/ccourses
      - VIRTUAL_HOST=api.kurser.ericwennerberg.se
      - LETSENCRYPT_HOST=api.kurser.ericwennerberg.se
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=ericwenn@gmail.com

  client:
    build: 
      context: client/.
      args:
        - REACT_APP_GRAPHL_URL=https://api.kurser.ericwennerberg.se

    ports:
      - 8902:80
    
    environment:
      - VIRTUAL_HOST=kurser.ericwennerberg.se
      - LETSENCRYPT_HOST=kurser.ericwennerberg.se
      - LETSENCRYPT_EMAIL=ericwenn@gmail.com
      - VIRTUAL_PORT=80

  mongo:
    image: mongo

networks:
  default:
    external:
      name: nginx-proxy
