version: '3.2'
services:
  api:
    image: ericwenn/chalmers-courses:api-1.0.1
  
    environment:
      - MONGO_URL=mongodb://mongo/ccourses
      - VIRTUAL_HOST=api.kurser.ericwennerberg.se
      - LETSENCRYPT_HOST=api.kurser.ericwennerberg.se
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=ericwenn@gmail.com

  client:
    image: ericwenn/chalmers-courses:client-1.0.1
    
    environment:
      - REACT_APP_GRAPHQL_URL=https://api.kurser.ericwennerberg.se
      - VIRTUAL_HOST=kurser.ericwennerberg.se
      - LETSENCRYPT_HOST=kurser.ericwennerberg.se
      - LETSENCRYPT_EMAIL=ericwenn@gmail.com
      - VIRTUAL_PORT=80

  mongo:
    image: mongo
    # ports:
    #   - 27017:27017

networks:
  default:
    external:
      name: nginx-proxy
